### ISSUE TITLE
preserve order feature

### ISSUE THREAD

**Issue by hoodie** [havarnov/multimap#13]
Hi there,
it would be really nice to have an optional feature that switches multimap from using `HashMap` to something like [LinkedHashMap](https://crates.io/crates/linked-hash-map) to preserve the order of items.

What do you think?

Update
nevermind, a BTreeMap would also do :D

**Comment by havarnov** [comment]
I agree that it would be cool to change the map implementation, but as it stands now there are only thirdparty traits for the collections in std. And there probably wont be any until rust has HKT.

One possibility would be to use a thirdparty map trait or a custom one, for v2 of MultiMap since this will be a braking change. And change to official traits when/if that happends for v3.

I'll have to think about it. What do you think?

**Comment by hoodie** [comment]
That sounds good. I just thought about this because yaml-rust has a similar feature which replaces the internal `BTreeMap` with a `LinkedHashMap`. Being a bit more flexible would be cool.
Perhaps MultiMap itself could be a trait that and then the crate provides something like a `BTreeMultiMap`, `HashMultiMap` and `LinkedMultiMap` etc

**Comment by havarnov** [comment]
I have thought about MultiMap being a trait, but I'm not convinced that that will be as smooth for the users of MultiMap as it can be. Here is a short proof of concept to show what I mean:

``` rust
use std::hash::Hash;
use std::collections::HashMap;
use std::collections::hash_map::RandomState;
use std::default::Default;

trait MultiMap<K, V>
    where K: Eq + Hash
{
    fn insert(&mut self, k: K, v: V);
}

impl<K, V> MultiMap<K, V> for HashMap<K, Vec<V>, RandomState>
    where K: Eq + Hash
{
    fn insert(&mut self, k: K, v: V)
    {
        match self.entry(k) {
            ::std::collections::hash_map::Entry::Occupied(mut entry) => {
                let values = entry.get_mut();
                values.push(v);
            },
            ::std::collections::hash_map::Entry::Vacant(entry) => {
                entry.insert(vec![v]);
            }
        }
    }
}

struct Foo<T>
    where T: MultiMap<u8, u8> + Default
{
    map: T
}

impl<T> Foo<T>
    where T: MultiMap<u8, u8> + Default
{
    fn new() -> Foo<T> {
        Foo {
            map: Default::default()
        }
    }

    fn insert(&mut self, k: u8, v: u8) {
        self.map.insert(k, v);
    }
}

fn main() {
    let mut m: HashMap<u8, Vec<u8>> = HashMap::new();
    m.insert(1, vec![42]);
    MultiMap::<_, _>::insert(&mut m, 2, 8);

    let mut f: Foo<HashMap<u8, Vec<u8>>> = Foo::new();
    f.map.insert(6, vec![42]);
    f.insert(4, 45);
}
```

If MultiMap is used directly the api is awkward if the method signatures are the same as methods implemented for the type MultiMap is generic for. On possibility could be to change the method names, e.g.: `MultiMap::insert_one()`.
If the trait is used from "inside" a impl of a generic struct, it's not that bad. Although it's not that convenient to instantiate such a struct, but I guess that's true for all generic structs.

And to be honest the MultiMap trait isn't that useful, if you really need a LinkedMultiMap you could just impl the methods you need for your specific need and not care about any MultiMap trait. 

I don't see the benefit of creating a LinkedMultiMap, BTreeMultiMap, etc, That will just be an reimplementation if MultiMap several times and could just be it's own crate. Since they don't share any code.

So to conclude, I think the best way forward is to impl MultiMap as a genric struct over some sort of Map trait. I'll see when/if I have time to work on it. Or maybe I'll just wait until there is an official Map trait in the standard library.

**Comment by hoodie** [comment]
Yes I agree, with trait I mostly meant that there would be a common interface to different implementations. Though this, as you say, can already be achieved differently :D
